### PR TITLE
Update Dockerfiles to build with buster

### PR DESCRIPTION
**Pull request by piersharding**
This branch is a starting point for the upgrade to Buster - all the images build, but have not been tested

### CODE REVIEW

**Comment by piersharding** [comment]
Hi -
I have pushed this up so that it doesn't get lost, just in case someone wishes to use it as a starting point for doing the Buster upgrade.

Cheers,
Piers.

**Review by Matteo04052017 — APPROVED** [review]
Thanks. I was about to create the link libboost_python3-py37.so.

The only think is that we should change the version of those docker images when pushing them to the repo.

**Comment by Matteo04052017** [comment]
Unfortunately, the pipeline started and pushed the new version with the old tag. Not sure what to do now... Besides one image building gives an error... I will look into that... but I don't know what to do for the old version overwritten....

**Comment by flyingfrog81** [comment]
did it run because of an error in the pipeline definition, and we must fix the pipeline before merging this? Also, shouldn't we do the release and upload to Nexus only on repo tagging?

**Comment by flyingfrog81** [comment]
The old 0.1.0 image should be fixed on Nexus as well. can we get it built and uploaded manually?

**Comment by Matteo04052017** [comment]
There were different problems. The first one was a link on the tango-dsconfig to make (which I solved). 
Then I run the old pipeline to restore the old versions. 
Now there is a problem in the docker login on nexus and nothing is working. 
Once nexus will come back online, I will push the tag 0.1.0 and a 0.2.0.

**Comment by piersharding** [comment]
Hi - one of the ways around this sort of thing is to tag builds with the commit hash only at the build phase, and then tag the commit hash with the semantic version in a version phase once all the tests have passed.
There should also be a step in the version phase that checks and fails if the version that is going to be pushed already exists to help guard against this.

**Comment by Matteo04052017** [comment]
Yes, that is the right behavior but, for the moment, I will put the "push" in a manual job.

**Pull request merged**
